### ISSUE TITLE
Change the default Project Name

### ISSUE THREAD

**Issue by drobertson123** [yowko/xUnit.net.TestGenerator#1]
Thanks for this tool.

I am hoping you can help me resolve one issue. The "Create Unit Tests" function always defaults to [Project]Tests. We need to change this default to follow our naming guidelines. It should actually be a simple change [Project].Tests with the dot between the project and tests.

At this point, I can't find any way to change this setting.

**Comment by yowko** [comment]
I can't find any way to change this setting, either.
But I found a clue that this setting in visual studio 2013 is in the resource file.
![image](https://cloud.githubusercontent.com/assets/3851540/26628232/d6fc7a8a-462f-11e7-96f7-b9d67617467b.png)
