### ISSUE TITLE
Add support for Visual Studio 2022

### ISSUE THREAD

**Issue by paule96** [yowko/xUnit.net.TestGenerator#10]
Hi,

could you add for visual studio 2022 please? That would be nice. In special with the latest feature for test generation.

Because I do not know much about visual studio extension development, I just can wish you good luck and hope you know what is todo.
If I can supply any help to resolve this issue, I would try it 🤷‍♀️

**Comment by yowko** [comment]
Hi,
I'm figuring out how to do that. Because Visual Studio is going 64-bit. 
I'll finish it asap.
Thank you.

**Comment by yowko** [comment]
@paule96 
Hi, I couldn't find any solution to make this extension will be able to work in both Visual Studio 2019 and 2022.
I upload a new extension for Visual Studio  2022. [xUnit.net.TestGenerator2022](https://marketplace.visualstudio.com/items?itemName=YowkoTsai.xunitnettestgenerator2022)

**Comment by paule96** [comment]
Thank you for your work and research 👍 will test this soon

**Comment by DanielHabenicht** [comment]
It works for me, so maybe you can remove the `preview` label so it can be found in the Marketplace search.

**Comment by yowko** [comment]
@DanielHabenicht 
I've changed the tag  from `0.1` to `1.0` and remove the `preview` label.
Thank you so much.
